=== Sayut61/Web_HW1/src/web/orange/orange.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="$LOCAL_SCHEMA$" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root" type="loc:rootType" xmlns:loc="$LOCAL_SCHEMA$"/>

  <xs:complexType name="visual_parametersType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="color"/>
        <xs:attribute type="xs:string" name="size"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="growing_tipsType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="temp"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="flowerType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="soil"/>
      <xs:element type="xs:string" name="origin"/>
      <xs:element type="loc:visual_parametersType" name="visual_parameters" xmlns:loc="$LOCAL_SCHEMA$"/>
      <xs:element type="loc:growing_tipsType" name="growing_tips" xmlns:loc="$LOCAL_SCHEMA$"/>
      <xs:element type="xs:string" name="multiplying"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="flowerCode"/>
  </xs:complexType>

  <xs:complexType name="rootType">
    <xs:sequence>
      <xs:element type="loc:flowerType" name="flower" xmlns:loc="$LOCAL_SCHEMA$"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Sayut61/Web_HW1/src/web/orange/orange.xml
<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="$LOCAL_SCHEMA$"
        xsi:noNamespaceSchemaLocation="orange.xsd">
<flower flowerCode="rm">
    <name> roza </name>
    <soil> grunt </soil>
    <origin> rus </origin>
    <visual_parameters color="" size=""> white 15 </visual_parameters>
    <growing_tips temp = ""> 25 </growing_tips>
    <multiplying> semena </multiplying>
</flower>
</root>
